### PR TITLE
Add preferences page, ability to edit font family, font size

### PR DESCRIPTION
**Pull request by drinchev**
Hey guys can you help me out and test the latest changes. I added a Preferences page and the ability to change font name, font size.

The preferences can be per project and global ( as the global ones are just defaults for future project, nothing more ).

cc @jsawo 

Related issues #4 #2 

Screenshot 2019-10-15 at 17 14 37

### CODE REVIEW

**Comment by fearlex** [comment]
Guys, would you mind referencing how can I test this ?

I checkout the main repo, then fetched the pull request, but still don't see your changes.

I added from Disk to my PHPStorm and on the dist folder all I see is version 0.91, no 1.0.

Sorry if this is a dumb question

**Comment by drinchev** [comment]
You need to build the project ( Set the Dev Environment to Plugin - check https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/setting_up_environment.html ).

image

Use Java 8 for the language version.

Then you need to click on the right button of `project-label.iml` and choose from the menu "Prepare plugin module for deployment".

image

This will create a "project-label.jar" file which you can later import as a plugin in your IDE via the Plugins page ). Note that you should "Uninstall" the Project Label plugin that you've installed before.

image

**Comment by fearlex** [comment]
Thanks, that helps. I will test this tonight and let you know.

**Comment by jsawo** [comment]
Looks really nice, will build it and give it a test drive tomorrow.

**Comment by jsawo** [comment]
Gotta say that the color picker is a great addition.
So I tried it out today (on Ubuntu) and two things jumped out. 

By default it tries to load Verdana font but since I don't have it installed, it loads some random serif font: 
linux_default_settings

When setting a large font size, the label gets cut:
linux_large_font

I think we should be able to automatically resize the whole widget to fit the font. 

Later today I'll be able to do some testing on a windows machine as well.

**Comment by jsawo** [comment]
one more thing - the thing I was thinking about regarding global and per-project settings
since font family and font size are saved per-project, I'd need to set those up for every project now:

linux_multiple_windows

I think that while colors and label text are expected to be set separately for each project, font size and family should be global

**Comment by drinchev** [comment]
Hey @jsawo thanks for checking. 

Just a note regarding global / per-project settings. Based on the IntelliJ API they claim that if you configure the plugin without a project

image

You will be able to specify values for Project Label that will be valid for **new projects**. It seems to me that this might be use for a way to save them as global variables. However I will have to check that behaviour and if it doesn't work will try to figure out something else.

Another thing is that I'm afraid that the widget's label in the status bar should grow on **heigh** if we make fonts with bigger size to render properly, which will most probably make the status bar ugly ( or if it is possible at all ). Will investigate that as well.

Stay tuned and thanks for your help.

**Comment by jsawo** [comment]
I'm pretty sure we can solve both of those problems. 
I seem to remember that while I was testing various ideas with this plugin I was able to resize the widget as needed, I'll have a little more time to dig around next week so if needed, I might be more helpful then.
As for the settings, I was thinking that we should be able to decide where to store which property. Currently all the properties are saved in the project folder but I'm pretty sure we can choose to save some of them globally. That, I think, would be much more intuitive for the user than changing the settings without project.

**Comment by jsawo** [comment]
@fearlex if you were unable to build this and still want to test, here's a built version:

[project-label_w_settings.zip](https://github.com/drinchev/project-label/files/3736267/project-label_w_settings.zip)

you just need to change the extension to .jar (github limitation) and install it just as @drinchev suggested

**Comment by fearlex** [comment]
@jsawo 

I wasn't able to test this because of work, but now you made it even easier. I will test it on a mac today/tonight for sure.

I'll let you know my findings.

Thanks you both for the hard work.

**Comment by drinchev** [comment]
Okay @jsawo I took your arguments and : 

**Fixed the text being not entered when the font size is bigger** 

Screenshot 2019-10-17 at 9 09 44
Screenshot 2019-10-17 at 9 09 18
Screenshot 2019-10-17 at 9 09 30

I think it might look ugly, but since it's a user preference it seems fine.

**Added font family and size as an application preference**

Screenshot 2019-10-17 at 17 37 20

I updated a bit the preferences panel and now you can set the font size / font family per project as well as a global setting.

Can I kindly ask you to check again and if it all looks good, let's release it ;)

**Comment by jsawo** [comment]
Hey that looks great. I'll give it a try tomorrow.

**Comment by fearlex** [comment]
@jsawo @drinchev 

I just tested this on Mac, OS: Mojave, and it looks great. I tried different simple scenarios and it worked perfect.

Is there a particular scenario that should be tested ?

Kudos on a great work, I wish I could know Java, so i could help out.

**Comment by jsawo** [comment]
Ok, here are some thoughts on the latest version. 
Global and project preferences seem to be working good.

On linux the default font is Serif, it doesn't look great but is fixable with global preferences.
linux_default_font
What would be better, I think, especially for new users, is defaulting to 'Dialog' font - this one is more readable, and afaik, everyone should have this one as it is provided by Intellij itself: 
linux_dialog_font

I've also noticed a weird little behavior in the preferences panel. When I change the font size by entering the value directly (not using the spinner thingy) and confirm it by pressing enter (instead of clicking the "OK" button), the dialog is closed but the font size is reverted to the previous value. I need to remove focus from the control to make it save the value. Weirdly enough, when changing the label text this does not happen - it will save changes without changing focus.
linux_settings
That's a little thing, nothing major, just something to be aware of.

One more thing - not sure how would we address it but...
Let's say I have 2 windows opened. Both are using global font family and size. In one of them, I'm changing the global font size and the widget is re-rendered. The other window is not updated. The only way to force the second widget to refresh is to either open/close the project window or open the settings panel and make some change there (won't refresh if there are no changes made).
I don't think we can automatically detect and properly react in such a case but maybe we could refresh the widget when closing the preferences panel so that just opening and closing the panel would do? Or maybe refresh when clicking on the widget (before opening properties)?

Otherwise, everything looks great to me.

**Comment by drinchev** [comment]
Thanks for reviewing all.

1. I changed the default font from **Serif** to **Dialog**
2. I made the UI to refresh on clicking the widget

However I'm not sure where the problem with the spinner comes from. I see most of the other plugins' configurations don't use spinner at all. Maybe I'll have to change that in the future or when I have time again :). The Spinner can be replaced with a simple input field, like it is in the *Editor* -> *Font* preferences.

image

Unfortunately I'm not doing that in this PR, but you guys can contribute if you like :) And thanks for the help.

I plan to release this tomorrow, btw.

**Comment by jsawo** [comment]
I'll try to tackle the font size spinner thing soon. But it's such a small issue that I don't think it should block the release.
Looking forward to the release :)

**Comment by drinchev** [comment]
So ... I have submitted the plugin to JetBrains. Waiting for 2 business days approval. Will keep you posted and close the related issues once the plugin is publicly available.

**Comment by drinchev** [comment]
The plugin was approved by JetBrains and is now available for download. 

However I noticed one bug that we've missed. The file for the project settings was renamed from `ProjectLabelPlugin.xml` to `project-label.xml` which means that each project that you already had configured must be reconfigured :(. Anyway don't plan to fix this, since it's already in the public and it will be worse to switch the file names now :P

**Comment by fearlex** [comment]
@drinchev Thanks for working on this. It looks amazing and I'm already using it in my IDE.

**Pull request merged**
