### PR TITLE
fixes and features

### PR DESCRIPTION
**Pull request by jsawo**
I've added a few things for my own use and thought you might want to pull those in. The main changes are:
- option to change font color so we can have e.g. dark text on light background
- option to change label text - defaults to project name if left empty - useful with long project names or multiple windows with similar project names
- options popup is now parented to the window so that you don't have to look for it on multi monitor setup
- fixed text measuring - text is now nicely centered (should close issue #3)
- fixed label duplication - happened when opening a new project in the same window (should close issue #1)
- font size is scaled with Idea UI (addresses issue #4 - but I'm thinking of adding a separate font size setting)
- changed font to the same that is used across Idea UI - that way there should be no problems with missing font + we get some UI consistency

### CODE REVIEW

**Comment by fearlex** [comment]
Let's see if it gets merged. Project last update was 4 years ago, unfortunately.

**Comment by drinchev** [comment]
Awesome and thanks for your contribution to this project. I'm merging this PR and will try to release it to the plugin repository ASAP.

**Comment by drinchev** [comment]
P.S. @fearlex although no work was done here recently, I haven't abandoned the project. The issues discussed, are just no useful for my use case, so I didn't work on them. I'm really happy that people are contributing so you are welcome to submit a PR.

**Comment by fearlex** [comment]
@drinchev, i’m glad you pull the PR, i saw it hadn’t been updated in 4 years so i mistakenly assumed it was abandoned. Glad to know I was wrong. I would contribute but i haven’t learned Java yet, i do mostly wordpress and reactJS. Thanks for an amazing little tool which helps so much.

**Comment by drinchev** [comment]
Guys checked the build of the plugin and it seems that the font-rendering is kinda worse now. The default font's size I guess is quite small and it is even less visible now. 

Screenshot 2019-10-14 at 14 31 29

I assume we'll have to make some other updates to the plugin, before we release that PR.

Does anyone want to make a PR for : 

1. Changing the font
2. Modifying the font size

I will try to work something over this weekend, however since @jsawo seems more competent in IntelliJ plugins I assume it might be easier to make the desired changes.

Also was wondering if it would be better to add a separate Preferences page for that plugin already in the "Preferences" window, instead of using the very same window. 

What do you think?

**Comment by jsawo** [comment]
Yeah, the font itself was changed so that might be the cause. I'll look into it. Unfortunately, I'm only able to test on linux and windows.

As for the preferences - I think that's a good idea. I'm not sure yet how exactly would that work given we'd want both global (font family and size) and per-project settings (colors and label).

(and tbh. I'm not that competent in this matter - just learning as I go)

**Comment by drinchev** [comment]
Can you @fearlex check the other PR that adds preference page and font size changes as well as font-name modification? 

https://github.com/drinchev/project-label/pull/6

**Comment by fearlex** [comment]
@drinchev 

Will do as soon as I get a chance. Thanks!

**Comment by ddnexus** [comment]
@jsavo Thank you for the PR!

**Pull request merged**
